"""Export a grounded scouting report as Markdown or PDF (PRD US-17, stretch S5).

The export never adds a number: it reformats the report text that already passed the
grounding validator and appends the fact sheet's receipts (sources with their as-of dates),
so a printed report still says where every figure came from.

PDFs use fpdf2's built-in Helvetica, which only covers Latin-1, so the few characters outside
it are spelled out ("€38.0m" becomes "EUR 38.0m") rather than bundling a font.
"""

from __future__ import annotations

import re

from fpdf import FPDF
from fpdf.enums import XPos, YPos

from scout.reports.facts import FactSheet

TITLE_PREFIX = "SCOUTING REPORT:"
# Characters outside Latin-1 that reports may contain: euro sign, dashes, curly quotes, minus.
_LATIN1 = str.maketrans(
    {
        "\u20ac": "EUR ",
        "\u2013": "-",
        "\u2014": "-",
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2212": "-",
    }
)
_SLUG = re.compile(r"[^a-z0-9]+")


def is_heading(line: str) -> bool:
    """Section headings in template reports are lines written in capitals."""
    stripped = line.strip()
    return bool(stripped) and stripped == stripped.upper() and any(c.isalpha() for c in stripped)


def filename(sheet: FactSheet, extension: str) -> str:
    """``scouting-report-<player>.<ext>``."""
    slug = _SLUG.sub("-", sheet.player_name.casefold()).strip("-") or str(sheet.player_id)
    return f"scouting-report-{slug}.{extension}"


def receipts_line(sheet: FactSheet) -> str:
    """Every source behind the sheet with its as-of date."""
    parts = [f"{r.source} (as of {(r.as_of or 'Not available')[:10]})" for r in sheet.sources]
    return "Sources: " + "; ".join(parts) + "."


def footer_line(sheet: FactSheet, engine: str) -> str:
    """Provenance note printed under every export."""
    return (
        f"Generated by PL Scout Engine from a grounded {engine} report; fact sheet as of "
        f"{sheet.as_of.isoformat()}. Personal, non-commercial use."
    )


def to_markdown(sheet: FactSheet, text: str, *, engine: str = "template") -> str:
    """Markdown version of a report: headings, bullets and the receipts."""
    out: list[str] = []
    header = True
    for raw in text.splitlines():
        line = raw.rstrip()
        if line.startswith(TITLE_PREFIX):
            out.append(f"# Scouting report: {line[len(TITLE_PREFIX) :].strip()}")
            out.append("")
            continue
        if is_heading(line):
            header = False
            out.append(f"## {line.strip()}")
            continue
        if header and line:
            out.append(f"{line}  ")  # keep the header facts on separate lines
            continue
        out.append(line)
    body = "\n".join(out).rstrip()
    return f"{body}\n\n---\n\n{receipts_line(sheet)}\n\n_{footer_line(sheet, engine)}_\n"


def latin1(text: str) -> str:
    """Text the PDF core font can print (characters outside Latin-1 spelled out)."""
    return text.translate(_LATIN1).encode("latin-1", "replace").decode("latin-1")


def to_pdf(sheet: FactSheet, text: str, *, engine: str = "template") -> bytes:
    """A one-column A4 PDF of the report with its receipts."""
    pdf = FPDF(format="A4")
    pdf.set_title(latin1(f"Scouting report: {sheet.player_name}"))
    pdf.set_author("PL Scout Engine")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    width = pdf.epw

    def write(w: float, h: float, value: str) -> None:
        pdf.multi_cell(w, h, value, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    for raw in text.splitlines():
        line = latin1(raw.rstrip())
        if raw.startswith(TITLE_PREFIX):
            pdf.set_font("helvetica", "B", 16)
            write(width, 8, latin1(f"Scouting report: {raw[len(TITLE_PREFIX) :].strip()}"))
            pdf.ln(2)
        elif is_heading(raw):
            pdf.ln(2)
            pdf.set_font("helvetica", "B", 11)
            write(width, 6, line)
        elif not line:
            pdf.ln(2)
        elif line.startswith("- "):
            pdf.set_font("helvetica", "", 10)
            pdf.set_x(pdf.l_margin + 4)
            write(width - 4, 5, f"- {line[2:]}")
        else:
            pdf.set_font("helvetica", "", 10)
            write(width, 5, line)
    pdf.ln(4)
    pdf.set_font("helvetica", "I", 8)
    write(width, 4, latin1(receipts_line(sheet)))
    write(width, 4, latin1(footer_line(sheet, engine)))
    return bytes(pdf.output())
