/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health
     * @description Report liveness and the warehouse version.
     */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * ErrorBody
     * @description Machine-readable error details.
     */
    ErrorBody: {
      /**
       * Code
       * @description Stable error code, e.g. 'not_found'.
       */
      code: string;
      /** Details */
      details?: {
        [key: string]: unknown;
      };
      /** Message */
      message: string;
    };
    /**
     * ErrorResponse
     * @description The single error schema returned by every endpoint.
     */
    ErrorResponse: {
      error: components["schemas"]["ErrorBody"];
    };
    /**
     * HealthResponse
     * @description Liveness plus warehouse version.
     */
    HealthResponse: {
      /**
       * Status
       * @constant
       */
      status: "ok";
      /**
       * Version
       * @description Engine version.
       */
      version: string;
      /**
       * Warehouse Version
       * @description Warehouse build identifier; null until `scout build` has run.
       */
      warehouse_version: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
